name: "IOS Development Release IPAs"

on:
  push:
    branches:
      - test

jobs:
  IOS-Build:
    name: IBuild and Release new IPA
    runs-on: macos-latest
    env:

    steps:
      # Set Checkout Action
      - name: Checkout Action
        uses: actions/checkout@v3

      # Install Development Certificate for X-Code
      - name: Install Xcode Development Certificate (IOS)
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.DEVELOPMENT_CERIFICATE_P12 }}
          p12-password: ${{ secrets.DEVELOPMENT_CERTI_PASS_P12 }}

      # Install Package Provisional Certificate
      - name: Install Development Profile (IOS-App_ID)
        env:
          DEV_APPID_PROFILE_CERTIFICATE_BASE64: ${{ secrets.DEV_APPID_PROFILE_CERTIFICATE }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          echo -n "$DEV_APPID_PROFILE_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      # Set-up Flutter for run the code
      - name: Install Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.7.12'
          channel: 'stable'

      # Get Packages
      - name: Pub Get
        run: flutter pub get

      # Fire command for Ios build
      - name: Development IOS Build
        run: |
          flutter build ios --release -t lib/main_dev.dart --flavor=dev

      # Swift dependency command for X-Code
      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme dev -configuration Release-dev

      # Build Ios Archive File
      - name: Build Archive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme dev -configuration Release-dev DEVELOPMENT_TEAM=335857SHPB  -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE=c123cf8d-57dc-4a50-9ad1-23eda788b0ba clean archive CODE_SIGN_IDENTITY="iPhone Developer: Riddhika Thaker (LZSYC5826J)"

      # Export .ipa form Archive file
      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/Runner/ExportOptions.plist

      # Upload Ios Artifact 1
      - name: Upload IOS Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: IOS Build Artifact
          path: build-output/ios/






